/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : leds.C
**     Project   : I2C_implementation
**     Processor : MCF51AC256ACLK
**     Component : BitsIO
**     Version   : Component 02.102, Driver 03.12, CPU db: 3.00.053
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 2012-11-06, 15:40
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This bean is set to work in Output direction only.
**     Settings  :
**         Port name                   : PTJ
**
**         Bit mask of the port        : 0x00F0
**         Number of bits/pins         : 4
**         Single bit numbers          : 0 to 3
**         Values range                : 0 to 15
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTJD      [0xFFFF801A]
**         Port control register       : PTJDD     [0xFFFF801B]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    27   |   PTJ4_DDATA0
**                    1      |    28   |   PTJ5_DDATA1
**                    2      |    29   |   PTJ6_DDATA2
**                    3      |    30   |   PTJ7_DDATA3
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         GetDir - bool leds_GetDir(void);
**         GetVal - byte leds_GetVal(void);
**         PutVal - void leds_PutVal(byte Val);
**         GetBit - bool leds_GetBit(byte Bit);
**         PutBit - void leds_PutBit(byte Bit, bool Val);
**         SetBit - void leds_SetBit(byte Bit);
**         ClrBit - void leds_ClrBit(byte Bit);
**         NegBit - void leds_NegBit(byte Bit);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE leds. */

#include "leds.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  leds_GetMsk (component BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte leds_Table[4] = {    /* Table of mask constants */
   0x10, 0x20, 0x40, 0x80
};

static byte leds_GetMsk (byte PinIndex)
{
  return (byte)(PinIndex<4 ? leds_Table[PinIndex] : 0); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  leds_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 15)
** ===================================================================
*/
byte leds_GetVal(void)
{
  return (byte)((getReg8(PTJD) & 0xF0) >> 4); /* Return port data */
}

/*
** ===================================================================
**     Method      :  leds_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 15)
**     Returns     : Nothing
** ===================================================================
*/
void leds_PutVal(byte Val)
{
  Val = (byte)((Val & 0x0F) << 4);     /* Mask and shift output value */
  setReg8(PTJD, (getReg8(PTJD) & (~0xF0)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  leds_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 3)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool leds_GetBit(byte Bit)
{
  byte const Mask = leds_GetMsk(Bit);  /* Temporary variable - bit mask to test */
  return (bool)((getReg8(PTJD) & Mask) == Mask); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  leds_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 3)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void leds_PutBit(byte Bit, bool Val)
{
  byte const Mask = leds_GetMsk(Bit);  /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTJD, Mask);           /* [bit (Bit+4)]=0x01 */
  } else { /* !Val */
    clrReg8Bits(PTJD, Mask);           /* [bit (Bit+4)]=0x00 */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  leds_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void leds_ClrBit(byte Bit)
{
  byte const Mask = leds_GetMsk(Bit);  /* Temporary variable - set bit mask */
  clrReg8Bits(PTJD, Mask);             /* [bit (Bit+4)]=0x00 */
}

/*
** ===================================================================
**     Method      :  leds_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void leds_SetBit(byte Bit)
{
  byte const Mask = leds_GetMsk(Bit);  /* Temporary variable - set bit mask */
  setReg8Bits(PTJD, Mask);             /* [bit (Bit+4)]=0x01 */
}

/*
** ===================================================================
**     Method      :  leds_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void leds_NegBit(byte Bit)
{
  byte const Mask = leds_GetMsk(Bit);  /* Temporary variable - set bit mask */
  invertReg8Bits(PTJD, Mask);          /* [bit (Bit+4)]=invert */
}

/*
** ===================================================================
**     Method      :  leds_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the bean.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the bean (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool leds_GetDir(void)

**  This method is implemented as a macro. See leds.h file.  **
*/


/* END leds. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
